# @package _global_
# Random sampling configuration

sampling:
  method: random
  predictor: ddpm_cache
  steps: 128
  noise_removal: True
  num_sample_batches: 8
  num_sample_log: 2
  semi_ar: False
  stride_length: 1
  num_strides: 1
  num_particles: 8  # Not used by random

